name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 wheel
          pip install -r requirements.txt
      - name: Install Ubuntu dependencies
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -yq install ttf-mscorefonts-installer
        if: matrix.os == 'ubuntu-latest'
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # check for all the other problems. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Generate Labels
        run: |
          python ./LabelGenerator.py
        if: matrix.os != 'macos-latest'
      - name: Archive generated PDF
        uses: actions/upload-artifact@v2
        with:
          name: generated-${{ matrix.os}}-${{ matrix.python-version }}
          path: ResistorLabels.pdf
          if-no-files-found: error
        if: matrix.os != 'macos-latest'
      - name: Generate Labels with roboto
        run: |
          python ./LabelGenerator.py --roboto
      - name: Archive generated PDF
        uses: actions/upload-artifact@v2
        with:
          name: generated-${{ matrix.os}}-${{ matrix.python-version }}-roboto
          path: ResistorLabels.pdf
          if-no-files-found: error
